### ISSUE TITLE
Session Synchronization Fails - Older session is updated in failed-over request

### ISSUE THREAD

**Issue by aravindvis** [hazelcast/hazelcast-tomcat-sessionmanager#10]
I am trying to implement a sticky session based load balancing across two Tomcat instances using the Hazelcast Tomcat Web Session Replication. For testing purposes, I have deployed the application on two different Tomcat instances and the load balancing is handled through Apache HTTPD (tried both mod_proxy and mod_jk). The jvmroute parameters and the mod-proxy settings are fine and the load balancing has no issues.

The problem is with the session replication across the two instances. When the first server (currently serving the request) goes down the request is sent to the second server. The Hazelcast cluster identifies that the session is through fail-over and is copying the session with the new session id (suffixed with the jvmroute parameter of the second server) - as described in the Hazelcast documentation https://github.com/hazelcast/hazelcast-tomcat-sessionmanager#sticky-sessions-and-tomcat) . However for the failed-over request, the session attributes are getting updated in the older session(failed over jvmroute) and not getting replicated resulting in the failure of the subsequent request.

I have gone through the documentation but unable to find a resolution at this point. 

After tracing the flow, able to determine that the handleTomcatSessionChange in com.hazelcast.session.HazelcastSessionChangeValve is being called correctly. The request.changeSessionId(newSessionId) call happens and post this if I display the value of the requestedsession id, the value is updated. However, the session id is not updated and this is resulting in the older id in a request.getSession().getId() call and thereby the application setting the values in the older session. The first request fails as one of the session variables are not present, but once this is handled, the subsequent requests goes through fine. However, we would not be able to trace this across the whole application. 

Version Used : Hazelcast 3.7.1
Tomcat Plugin: 1.0.2
Tomcat Version: 7.0.40
Apache HTTPD: 2.4

**Comment by emre-aydin** [comment]
@aravindvis 
We have added tests for the failover scenario and manually tested as well. There seems to be no problems related to failover. Could you provide a test case or sample code to reproduce your issue?

**Comment by emre-aydin** [comment]
@aravindvis Closing the issue as we have not heard back from you. If you still have problems, feel free to re-open this issue.
