### ISSUE TITLE
tomcat startup failing due to SSL config not getting picked up 

### ISSUE THREAD

**Issue by shashank929** [hazelcast/hazelcast-tomcat-sessionmanager#106]
I am trying to use hazelcast-tomcat7-sessionmanager in client-server mode by connecting to hazelcast cluster which is running enterprise version 3.12. I am seeing failure in the server startup due to connection failure which is due to SSL connection not being picked up and is rejected by the hz server. But if you carefully see the logs then you can observe that the second thread hz.client_1 (after first failed one - hz.client_0) manages to establish connection successfully and when comparing the logs I can see that the second thread did pick up the SSL Enabled configuration. 

here are the logs:
INFO: Initializing ProtocolHandler ["http-bio-9443"]
Dec 24, 2020 6:43:26 PM com.springsource.tcserver.serviceability.rmi.JmxSocketListener init
INFO: Started up JMX registry on 127.0.0.1:18443 in 67 ms
Dec 24, 2020 6:43:26 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Dec 24, 2020 6:43:26 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Enigma/Codex
Dec 24, 2020 6:43:26 PM org.apache.catalina.startup.HostConfig start
FINE: HostConfig: Processing START
Dec 24, 2020 6:43:26 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /release/test/app/testBranch/test
Dec 24, 2020 6:43:38 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
Dec 24, 2020 6:43:38 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags/form is already defined
Dec 24, 2020 6:43:38 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.owasp.org/index.php/Category:OWASP_Enterprise_Security_API is already defined
Dec 24, 2020 6:43:38 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Dec 24, 2020 6:43:57 PM com.hazelcast.client.HazelcastClient
INFO: hz.client_0 [testapp] [3.12] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Dec 24, 2020 6:43:58 PM com.hazelcast.client.spi.ClientInvocationService
INFO: hz.client_0 [testapp] [3.12] Running with 2 response threads, dynamic=false
Dec 24, 2020 6:43:58 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is STARTING
Dec 24, 2020 6:43:58 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is STARTED
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to cluster with name: testapp
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver004.test.com]:5701 as owner member
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver004.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver006.test.com]:5701 as owner member
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver006.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver005.test.com]:5701 as owner member
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver005.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:43:58 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Unable to get live cluster connection, retry in 3000 ms, attempt 1 of 2.
Dec 24, 2020 6:44:01 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver004.test.com]:5701 as owner member
Dec 24, 2020 6:44:01 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver004.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:44:01 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver006.test.com]:5701 as owner member
Dec 24, 2020 6:44:01 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver006.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:44:01 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [testapp] [3.12] Trying to connect to [hzserver005.test.com]:5701 as owner member
Dec 24, 2020 6:44:02 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Exception during initial connection to [hzserver005.test.com]:5701: com.hazelcast.core.HazelcastException: java.io.IOException: Packet not sent to null
Dec 24, 2020 6:44:02 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Unable to get live cluster connection, attempt 2 of 2.
Dec 24, 2020 6:44:02 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Unable to connect to any address for cluster: testapp. The following addresses were tried: [[hzserver005.test.com]:5701, [hzserver004.test.com]:5701, [hzserver006.test.com]:5701]
Dec 24, 2020 6:44:02 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [testapp] [3.12] Could not connect to any cluster, shutting down the client: Unable to connect to any cluster.
Dec 24, 2020 6:44:02 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is SHUTTING_DOWN
Dec 24, 2020 6:44:02 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is SHUTDOWN
Dec 24, 2020 6:44:02 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: The session manager failed to start
org.apache.catalina.LifecycleException: Failed to start component [com.hazelcast.session.HazelcastSessionManager[/test]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5643)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:133)
        at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:156)
        at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:145)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:873)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Unable to connect to any cluster.
        at com.hazelcast.session.HazelcastInstanceFactory.getHazelcastInstance(HazelcastInstanceFactory.java:44)
        at com.hazelcast.session.HazelcastSessionManager.startInternal(HazelcastSessionManager.java:93)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 16 more

Dec 24, 2020 6:44:02 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/test] startup failed due to previous errors
Dec 24, 2020 6:44:02 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/test] appears to have started a thread named [pool-59-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Dec 24, 2020 6:44:02 PM org.apache.catalina.startup.HostConfig addWatchedResources
FINE: Watching WatchedResource '/release/test/app/testBranch/test/WEB-INF/web.xml'
Dec 24, 2020 6:44:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /release/test/app/testBranch/test has finished in 35,531 ms
Dec 24, 2020 6:44:02 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /release/test/app/testBranch/verificationchecksums
Dec 24, 2020 6:44:06 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Dec 24, 2020 6:44:06 PM com.hazelcast.client.HazelcastClient
INFO: hz.client_1 [testapp] [3.12] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Dec 24, 2020 6:44:06 PM com.hazelcast.client.spi.ClientInvocationService
INFO: hz.client_1 [testapp] [3.12] Running with 2 response threads, dynamic=false
Dec 24, 2020 6:44:06 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is STARTING
Dec 24, 2020 6:44:06 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is STARTED
Dec 24, 2020 6:44:06 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_1 [testapp] [3.12] Trying to connect to cluster with name: testapp
Dec 24, 2020 6:44:06 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_1 [testapp] [3.12] Trying to connect to [hzserver004.test.com]:5701 as owner member
**Dec 24, 2020 6:44:06 PM com.hazelcast.client.ClientExtension
INFO: SSL is enabled**
Dec 24, 2020 6:44:06 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_1 [testapp] [3.12] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/10.211.135.192:35543->hzserver004.test.com/10.207.217.232:5701}, remoteEndpoint=[10.207.217.232]:5701, lastReadTime=2020-12-24 18:44:06.478, lastWriteTime=2020-12-24 18:44:06.453, closedTime=never, connected server version=3.12.2-test3-1} as owner with principal ClientPrincipal{uuid='2afd1adf-328f-4b6b-a234-89cff4a9c20c', ownerUuid='8e2c5c02-d466-4051-8a6b-ec4b50e2896a'}
Dec 24, 2020 6:44:06 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_1 [testapp] [3.12] Authenticated with server [10.207.217.232]:5701, server version:3.12.2-test3-1 Local address: /10.211.135.192:35543
Dec 24, 2020 6:44:06 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_1 [testapp] [3.12]

Members [3] {
        Member [10.207.221.158]:5701 - 9809757a-ff6b-42e5-85ef-29195ed4fcad
        Member [10.207.221.77]:5701 - 2f6ad55f-2230-41fd-9795-602ff2a7fd60
        Member [10.207.217.232]:5701 - 8e2c5c02-d466-4051-8a6b-ec4b50e2896a
}

Dec 24, 2020 6:44:06 PM com.hazelcast.core.LifecycleService
INFO: hz.client_1 [testapp] [3.12] HazelcastClient 3.12 (20190409 - f68a315, 915d83a) is CLIENT_CONNECTED
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: hz.client_1 [testapp] [3.12] Diagnostics started
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.BuildInfoPlugin
INFO: hz.client_1 [testapp] [3.12] Plugin:active
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.ConfigPropertiesPlugin
INFO: hz.client_1 [testapp] [3.12] Plugin:active
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.SystemPropertiesPlugin
INFO: hz.client_1 [testapp] [3.12] Plugin:active
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.MetricsPlugin
INFO: hz.client_1 [testapp] [3.12] Plugin:active, period-millis:60000
Dec 24, 2020 6:44:06 PM com.hazelcast.internal.diagnostics.SystemLogPlugin
INFO: hz.client_1 [testapp] [3.12] Plugin:active: logPartitions:false
**Dec 24, 2020 6:44:06 PM com.hazelcast.client.ClientExtension
INFO: SSL is enabled**
Dec 24, 2020 6:44:06 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_1 [testapp] [3.12] Authenticated with server [10.207.221.158]:5701, server version:3.12.2-test3-1 Local address: /10.211.135.192:57959
Dec 24, 2020 6:44:06 PM com.hazelcast.session.HazelcastSessionManager startInternal
INFO: HazelcastSessionManager started...
Dec 24, 2020 6:44:06 PM org.apache.catalina.startup.HostConfig addWatchedResources
FINE: Watching WatchedResource '/release/test/app/testBranch/verificationchecksums/WEB-INF/web.xml'
Dec 24, 2020 6:44:06 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /release/test/app/testBranch/verificationchecksums has finished in 4,533 ms
Dec 24, 2020 6:44:06 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-9443"]
Dec 24, 2020 6:44:06 PM com.test.tcserver.properties.SystemPropertiesExporter lifecycleEvent
INFO: Effective Properties written to /mware/tcServerApps/test/conf/effectiveProperties.xml
**Dec 24, 2020 6:44:07 PM com.hazelcast.client.ClientExtension
INFO: SSL is enabled**
Dec 24, 2020 6:44:07 PM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_1 [testapp] [3.12] Authenticated with server [10.207.221.77]:5701, server version:3.12.2-test3-1 Local address: /10.211.135.192:57535
Dec 24, 2020 6:44:57 PM org.apache.catalina.loader.WebappClassLoaderBase findResourceInternal
INFO: Illegal access: this web application instance has been stopped already.  Could not load TestConfig.properties.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
Dec 24, 2020 6:44:57 PM org.apache.catalina.loader.WebappClassLoaderBase loadClass

I have highlighted the difference I've observed between the thead which failed connection and the one which went through. Seems to be about the com.hazelcast.client.ClientExtension not being loaded which didn't let the SSL being enabled. 

Below is my hazelcast-config.xml. Can you please give me some pointer as to what can be the cause of this issue?
I am using hazelcast-tomcat7-sessionmanager-1.1.3.jar but tried hazelcast-tomcat7-sessionmanager-1.1.4.jar as well.

`<?xml version="1.0"?>
<hazelcast-client xmlns="http://www.hazelcast.com/schema/client-config"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                  http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.12.xsd">

    <group>
        <name>testapp</name>
        <password>testappsecret123</password>
    </group>

    <network>
        <ssl enabled="true">
            <factory-class-name>com.hazelcast.nio.ssl.BasicSSLContextFactory</factory-class-name>
            <properties>
                <property name="protocol">TLS</property>
                <property name="mutualAuthentication">REQUIRED</property>
                <property name="keyStore">/test/certs/hazelcast-client-keystore.jks</property>
                <property name="keyStorePassword">pwd</property>
                <property name="keyStoreType">JKS</property>

                
                <property name="trustStore">/test/certs/generic_client_trust.jks</property>
                <property name="trustStorePassword">pwd</property>
                <property name="trustStoreType">JKS</property>
            </properties>
        </ssl>
        <cluster-members>
            <address>hzserver004.test.com:5701</address>
                <address>hzserver005.test.com:5701</address>
                <address>hzserver006.test.com:5701</address>
        </cluster-members>
    </network>
   </hazelcast-client>`

**Comment by shashank929** [comment]
Can someone please provide any pointers on this issue as to how loading of ClientExtension works which is not working in my case and hence SSL config is not getting picked up?

**Comment by alparslanavci** [comment]
Hi @shashank929, could you please let us know how you start two different clients? Are there multiple web deployments under the same Tomcat container?

**Comment by shashank929** [comment]
Hi @alparslanavci , sorry for not responding earlier. I was able to get the hazelcast enterprise support for this and we somehow were able to reproduce the issue and get the [fix](https://github.com/hazelcast/hazelcast/pull/18103) checked-in by them in the hazelcast repo.

**Comment by alparslanavci** [comment]
@shashank929 thanks for the clarification. Closing the issue.
