### ISSUE TITLE
Publish jars to Maven Repository

### ISSUE THREAD

**Issue by guerrillalg** [hazelcast/hazelcast-tomcat-sessionmanager#11]
Basically, we need to include those libs into our maven project, however they are not publichsed yet. Which is making some inconvenience. Are you planning to publish them to maven?

**Comment by bilalyasar** [comment]
seems something go wrong with oss nexus release plugin. i have deployed again.
https://oss.sonatype.org/content/groups/staging/com/hazelcast/hazelcast-tomcat8-sessionmanager/1.0.3/
It is available under sonatype and It should be available in maven soon:
https://repo.maven.apache.org/maven2/com/hazelcast/hazelcast-tomcat8-sessionmanager/

**Comment by guerrillalg** [comment]
OK, great then. Then it would be nice to put them to the docs.
