### ISSUE TITLE
Session data loss during failover

### ISSUE THREAD

**Issue by Anya1001** [hazelcast/hazelcast-tomcat-sessionmanager#18]
During failover next faulty behavior was observed:
- Node 1 Session was created. SessionID AAA.node1 was assigned
- Session variable A with data 111 was created
- Node 1 was killed
- Node 2 shows session variable A with correct data and **same sessionID as before** (AAA.node1)
- Trying to add session variable B with data 222 -> ERROR
New sessionID is assigned (a bit too late) ex. AAA.node1 and session variable B is lost. Session variable A is still present

**Comment by emre-aydin** [comment]
Hi @Anya1001 

Which version of Tomcat and which version of Hazelcast Tomcat Session Manager are you using? Can you also share the following please?

* The exact error message along with its stacktrace
* Your Tomcat configuration, specifically the parts you configure Hazelcast Tomcat Session Manager

**Comment by emre-aydin** [comment]
@Anya1001  I'm closing the issue as we haven't heard back from you. Feel free to reopen the issue if you still have the problem.
