### ISSUE TITLE
com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-X commited key:null #

### ISSUE THREAD

**Issue by wellprado** [hazelcast/hazelcast-tomcat-sessionmanager#25]
Hi guys,

I did a long search but unfortunately I did not find anything and I do not know if it can be a problem or configuration.

Everything seems to be work normal, session replication and so on but, every time a Session is created in tomcat, the message below is written in the log ...

```
15-May-2017 19:34:45.961 INFO [ajp-nio-8009-exec-1] com.hazelcast.session.HazelcastSessionManager.findSession Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null
15-May-2017 19:34:45.961 INFO [ajp-nio-8009-exec-2] com.hazelcast.session.HazelcastSessionManager.findSession Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null
15-May-2017 19:34:45.962 INFO [ajp-nio-8009-exec-1] com.hazelcast.session.HazelcastSessionManager.findSession No Session found for:A738487E57F23BF5C3C042E8EBA467E6.tomcat1
15-May-2017 19:34:45.962 INFO [ajp-nio-8009-exec-2] com.hazelcast.session.HazelcastSessionManager.findSession No Session found for:A738487E57F23BF5C3C042E8EBA467E6.tomcat1

15-May-2017 19:35:40.399 INFO [ajp-nio-8009-exec-3] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-3 commited key:null
15-May-2017 19:36:09.526 INFO [ajp-nio-8009-exec-7] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-7 commited key:null
15-May-2017 19:36:20.598 INFO [ajp-nio-8009-exec-1] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-1 commited key:null
15-May-2017 19:36:26.951 INFO [ajp-nio-8009-exec-9] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-9 commited key:null
15-May-2017 19:36:36.814 INFO [ajp-nio-8009-exec-6] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-6 commited key:null
15-May-2017 19:36:56.453 INFO [ajp-nio-8009-exec-6] com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-6 commited key:null
...
```

And each page the user navigates, the message:
`com.hazelcast.session.HazelcastSessionManager.commit Thread name:ajp-nio-8009-exec-6 commited key:null`

continue all the time....
Is that some problem ?

My env 64 bits: Linux RedHat 7.3, Tomcat 8.5, hazelcast-tomcat85-sessionmanager-1.1.jar, hazelcast-all-3.8.jar

Thank you very much!

**Comment by emre-aydin** [comment]
Hi @wellprado 

That log message is a wrong message. It has been fixed in version `1.1.1` of `hazelcast-tomcat85-sessionmanager`. If you upgrade your version, it should not be printed anymore. In any case, it is not a problem on your side, just a wrong log message.

**Comment by wellprado** [comment]
Hi @emre-aydin ,

  Thank you very much. I did exactly what you said and for now the message didn't appear any more!!!
  The only new situation after the upgrade to version 1.1.1 is the message below are logged many many time:

2017-06-19 15:09:44.035  INFO 20736 --- [ration.thread-0] c.i.o.SplitBrainMergeValidationOperation : [10.60.60.6]:5710 [hazelepp] [3.8] Ignoring join check from [10.60.60.5]:5701, because this node is not master...
2017-06-19 15:09:44.036  INFO 20736 --- [ration.thread-0] c.i.o.SplitBrainMergeValidationOperation : [10.60.60.6]:5710 [hazelepp] [3.8] Ignoring join check from [10.60.60.5]:5701, because this node is not master...
19-Jun-2017 15:09:59.727 INFO [hz.SESSION-REPLICATION-INSTANCE.priority-generic-operation.thread-0] com.hazelcast.internal.cluster.impl.operations.SplitBrainMergeValidationOperation.null [10.60.60.6]:5701 [dev] [3.8] Ignoring join check from [10.60.60.5]:5710, because this node is not master...
2017-06-19 15:11:44.035  INFO 20736 --- [ration.thread-0] c.i.o.SplitBrainMergeValidationOperation : [10.60.60.6]:5710 [hazelepp] [3.8] Ignoring join check from [10.60.60.5]:5701, because this node is not master...
2017-06-19 15:11:44.036  INFO 20736 --- [ration.thread-0] c.i.o.SplitBrainMergeValidationOperation : [10.60.60.6]:5710 [hazelepp] [3.8] Ignoring join check from [10.60.60.5]:5701, because this node is not master...


 Is that ok ? 

Regards

**Comment by emre-aydin** [comment]
@wellprado, it seems you have a slow network connection between the nodes and this causes a split brain. The log messages seem to indicate that. Are you still seeing the log messages? Are your nodes in the same data center? Does your application function normally?

**Comment by wellprado** [comment]
Hi, @emre-aydin ,

   The nodes are in  virtual machine in the same Physical host (10Gbit network ). 
   This messages are intermittent. As we stopped the nodes in very rare case, I don't know what to say about the frequency. I will plain to reboot them asap and I after that I will put the information here again.

Thank you

**Comment by emre-aydin** [comment]
@wellprado do you have any updates for us?

**Comment by mesutcelik** [comment]
Hi @wellprado ,
do you have any update?

**Comment by emre-aydin** [comment]
Closing the issue as we didn't hear back from you. Feel free to re-open if you still have the same issue.
