### ISSUE TITLE
Spring Boot support

### ISSUE THREAD

**Issue by stojsavljevic** [hazelcast/hazelcast-tomcat-sessionmanager#30]
Hi,

Is it possible to use this project together with Spring Boot and Java configuration?
If so, can you please provide a sample or instructions on how to configure it?

Thanks.

**Comment by mesutcelik** [comment]
Hi @stojsavljevic,

There is unfortunately no spring boot specific example but here is how you can [configure](https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/blob/master/tomcat85/src/test/java/com/hazelcast/session/Tomcat85Configurator.java#L26) embedded Tomcat in our test suite. 

I hope that helps.
