### ISSUE TITLE
Session Synchronization Fails

### ISSUE THREAD

**Issue by yongschoi** [hazelcast/hazelcast-tomcat-sessionmanager#31]
The same phenomenon occurs with the following issues.
https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/issues/10

In my case, Apache(1EA) - ajp - tomcat(4EA) with hazelcast-tomcat-sessionmanager.

If you click after 2 or 3 seconds after Tomcat is shut down, it works normally. 
If you click on Tomcat at the time of shut down, the session ID is changed and session clustering does not work.

===== Normal Case =====
Tomcat 1> SESSION ID : A16FAD3A97C4FC28312CAC005CA80488.worker4009
(Tomcat 1 shut down)
(Click after 2~3 seconds --> Session Synchronization)
Tomcat 2> SESSION ID : A16FAD3A97C4FC28312CAC005CA80488.worker5009

but,
===== Abnormal Case =====
Tomcat 1> SESSION ID : 2E593562D6A17FA8236EADDBAD7706FB.worker5009 
(Tomcat 1 shut down)
(If click Immediately --> Maybe, No Session Synchronization??? so new session)
Tomcat 2> SESSION ID : 86527A93CAEF4A2D380AB90FBC1F6A02.worker4009

Of course, backup-count = 1 in hazelcast-default.xml

Thank you in advance.

hazelcast-all-3.8.5
hazelcast-tomcat8-sessionmanager-1.1.2.jar

---------------------------- Normal log detail ----------------------------

20-Sep-2017 20:05:50.531 INFO [hz.SESSION-REPLICATION-INSTANCE.cached.thread-4]
com.hazelcast.transaction.TransactionManagerService.null [XX.XX.XXX.XXX]:5702 
[nip] [3.8.5] Committing/rolling-back alive transactions of Member [XX.XX.XXX.XXX]:5701 
7171e37e-711c-43d1-ac8f-649393b02a20, UUID: 7171e37e-711c-43d1-ac8f-649393b02a20

20-Sep-2017 20:05:50.700 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] 
com.hazelcast.internal.partition.InternalPartitionService.null [XX.XX.XXX.XXX]:5702 
[nip] [3.8.5] Fetching most recent partition table! my version: 950

20-Sep-2017 20:05:50.703 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] 
com.hazelcast.internal.partition.InternalPartitionService.null [XX.XX.XXX.XXX]:5702 
[nip] [3.8.5] Most recent partition table version: 950

20-Sep-2017 20:05:50.733 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] 
com.hazelcast.internal.partition.impl.MigrationManager.null [XX.XX.XXX.XXX]:5702 
[nip] [3.8.5] Partition balance is ok, no need to re-partition cluster data...

20-Sep-2017 20:07:50.796 INFO [ajp-apr-5009-exec-2] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.
Some failover occured so reading session from Hazelcast map:null

2017-09-20 20:07:51,213 234925 [ajp-apr-5009-exec-2] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|A16FAD3A97C4FC28312CAC005CA80488.worker4009|

2017-09-20 20:07:53,878 237590 [ajp-apr-5009-exec-3] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|A16FAD3A97C4FC28312CAC005CA80488.worker5009|

2017-09-20 20:07:55,346 239058 [ajp-apr-5009-exec-4] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|A16FAD3A97C4FC28312CAC005CA80488.worker5009|

---------------------------- Abnormal log detail ----------------------------

20-Sep-2017 19:41:06.104 INFO [hz.SESSION-REPLICATION-INSTANCE.cached.thread-2]
com.hazelcast.transaction.TransactionManagerService.null [XX.XX.XXX.XXX]:5701 
[nip] [3.8.5] Committing/rolling-back alive transactions of Member [XX.XX.XXX.XXX]:5702 
47c4c6b6-ae25-4b30-a000-587fca5c52f2, UUID: 47c4c6b6-ae25-4b30-a000-587fca5c52f2

20-Sep-2017 19:41:06.103 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] 
com.hazelcast.internal.partition.impl.MigrationManager.null [XX.XX.XXX.XXX]:5701 
[nip] [3.8.5] Partition balance is ok, no need to re-partition cluster data...

20-Sep-2017 19:41:07.134 INFO [hz.SESSION-REPLICATION-INSTANCE.migration] 
com.hazelcast.internal.partition.impl.MigrationThread.null [XX.XX.XXX.XXX]:5701 
[nip] [3.8.5] All migration tasks have been completed, queues are empty.

20-Sep-2017 19:41:07.930 INFO [ajp-apr-4009-exec-4] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.
Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:07.958 INFO [ajp-apr-4009-exec-3] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.
Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:07.960 INFO [ajp-apr-4009-exec-3] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

20-Sep-2017 19:41:07.962 INFO [ajp-apr-4009-exec-3] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.
Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:07.965 INFO [ajp-apr-4009-exec-3] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

2017-09-20 19:41:08,354 97676 [ajp-apr-4009-exec-4] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|2E593562D6A17FA8236EADDBAD7706FB.worker5009|

2017-09-20 19:41:08,354 97676 [ajp-apr-4009-exec-3] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|537B161FE5E5BD20CDBF45B64F32997B.worker4009|

20-Sep-2017 19:41:09.202 INFO [ajp-apr-4009-exec-7] 
com.hazelcast.session.HazelcastSessionManager.findSession Sticky 
Session is currently enabled.Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:09.206 INFO [ajp-apr-4009-exec-7] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

20-Sep-2017 19:41:09.208 INFO [ajp-apr-4009-exec-7] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.
Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:09.209 INFO [ajp-apr-4009-exec-7] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

2017-09-20 19:41:09,215 98537 [ajp-apr-4009-exec-7] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|67B86BCA65097729135D9F4FEDCB6A46.worker4009|

20-Sep-2017 19:41:09.790 INFO [ajp-apr-4009-exec-10] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:09.791 INFO [ajp-apr-4009-exec-10] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

20-Sep-2017 19:41:09.793 INFO [ajp-apr-4009-exec-10] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:09.796 INFO [ajp-apr-4009-exec-10] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

2017-09-20 19:41:09,799 99121 [ajp-apr-4009-exec-10] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|0F190873930FDC897BA78382B05992B0.worker4009|

20-Sep-2017 19:41:10.556 INFO [ajp-apr-4009-exec-1] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:10.560 INFO [ajp-apr-4009-exec-1] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

20-Sep-2017 19:41:10.563 INFO [ajp-apr-4009-exec-1] 
com.hazelcast.session.HazelcastSessionManager.findSession 
Sticky Session is currently enabled.Some failover occured so reading session from Hazelcast map:null

20-Sep-2017 19:41:10.566 INFO [ajp-apr-4009-exec-1] 
com.hazelcast.session.HazelcastSessionManager.findSession 
No Session found for:2E593562D6A17FA8236EADDBAD7706FB.worker5009

2017-09-20 19:41:10,570 99892 [ajp-apr-4009-exec-1] WARN  
yongs.temp.interceptor.LoginInterceptor ::: SESSION ID ==>|86527A93CAEF4A2D380AB90FBC1F6A02.worker4009|

**Comment by mrtinkz** [comment]
I guess, we are in the same boat, I asked a similar question on stackoverflow few weeks back. But I am stuck in the same place.

**Comment by emre-aydin** [comment]
@mrtinkz are you also experiencing the issue when you try immediately after the node goes down, and not experiencing it if you try 2-3 seconds later as @yongschoi does?

**Comment by emre-aydin** [comment]
@yongschoi @mrtinkz I have just tried failover with Apache 2.4 and Tomcat 8.5 - it works. I have also created a docker compose template, you can see it in this branch on my fork: https://github.com/emre-aydin/hazelcast-docker-samples/tree/httpd/manager-based-session-replication/httpd

Please note the `jvmRoute` parameter in these two lines:
https://github.com/emre-aydin/hazelcast-docker-samples/blob/httpd/manager-based-session-replication/httpd/server-1.xml#L105
https://github.com/emre-aydin/hazelcast-docker-samples/blob/httpd/manager-based-session-replication/httpd/server-2.xml#L105

And the relevant line on the Apache 2.4 VirtualHost configuration:

https://github.com/emre-aydin/hazelcast-docker-samples/blob/httpd/manager-based-session-replication/httpd/httpd-vhosts.conf#L36-L37

Can you please check both your Apache and Tomcat configurations to see if they are correct? If it still doesn't work, can you share the relevant reverse proxy/load balancing configuration from the Apache configuration and the `jvmRoute` parameter from your Tomcat's `server.xml`?

**Comment by yongschoi** [comment]
Dear Emre Aydin
 
Thank you for your mail. 
 
In my case,
. Tomcat / server.xml : &lt;Engine name="Catalina" defaultHost="localhost" jvmRoute="worker1"&gt;
. Apache / workers.properties : worker.worker1.type=ajp13
 
There is no problem with the configuration. I think. 
 
Session Synchronization Fails (#31) issues have been resolved with the following settings.
. Tomcat / context.xml : &lt;Manager className="com.hazelcast.session.HazelcastSessionManager" deferredWrite="false" /&gt;
 
But, I'm not sure completely.
Because, deferredWrite ="true" is default. Please give your opinion. 
 
Let me ask you an additional question. 
 
Deploying Client-Server for Tomcat 
In this deployment type, if all the Hazelcast Session Servers are dead, the existing session is maintained, but no new session is created.
Although the Hazelcast Session Server is alive, no new session is created.Finally, Application Server must be restarted.


Do you have a solution? Or are there options?



Of course, hazelcast-tomcat8-sessionmanager-1.1.2.jar is well used.
 
Thanks, a lot.
 
 
블로그서명주변인 블로그
나는요.... 
-----Original Message-----

**Comment by emre-aydin** [comment]
@yongschoi `deferredWrite` might explain what was happening in the first scenario described in your first message. When `deferredWrite` is enabled, the session values are not updated in the cluster until the request is completely processed by Tomcat. If the server goes down before the valve is executed, session data will be lost. If losing session data occasionally in a crash scenario (due to this unlucky timing) is acceptable, I would suggest enabling `deferredWrite` as it is more performant. Otherwise, stick to disabling `deferredWrite`, in which case all session values are directly updated in the cluster. I believe the performance will still be good enough, you can think of enabling it in case you need better performance.

Regarding your second question, I didn't understand it completely. Do you mean that once a cluster goes down and up back again, the clients do not create a session on it unless the application server is restarted?

**Comment by yongschoi** [comment]
Yes, that's right.
Although a cluster goes down and up back again, Application Server(Tomcat) can not connect to cluster.
 
This is an additional suggestion.
If a cluster goes up, Tomcat connect to a cluster without restart. 
 
Thanks in advance. 
블로그서명주변인 블로그
나는요.... 
-----Original Message-----

**Comment by emre-aydin** [comment]
@yongschoi, 

You can increase the `connection-attempt-limit` for the client. This way, it will connect to the cluster when it's up again. 

Default value of it is `2`. If you set it to `0`, the client will try to reconnect back to the cluster forever. See [this section in the README](https://github.com/hazelcast/hazelcast-tomcat-sessionmanager#deploying-client-server-for-tomcat) which explains how to use a custom XML configuration for the client. Default location for a custom client  configuration file is `hazelcast-client-default.xml` as can be seen [here](https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/blob/0a2d9e6ae43b0a645303cc8d4a26f40cb384e381/tomcat-core/src/main/java/com/hazelcast/session/ClientServerLifecycleListener.java#L24), so you can just have a client configuration file with that name on your classpath. 

Also, see the section on [Hazelcast Reference Manual](http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#setting-connection-attempt-limit) for setting the connection attempt limit of the client using XML configuration.

**Comment by yongschoi** [comment]
Great !

Thanks for your help.-----Original Message-----

**Comment by emre-aydin** [comment]
@yongschoi Glad to hear your problem is resolved, I'm closing the issue. @mrtinkz can you please create another issue with your configuration and any relevant info that will help us solve your problem?

**Comment by mrtinkz** [comment]
My apologies for delayed response. I figured the configuration needed both jsessionid and the hazelcast.sessionid. The session replication works great and I do not see any other reason to create a new issues. Thanks for helping me out.

**Comment by vir2610** [comment]
@mrtinkz , can you please show me high level configuration because my application doesn't even create jsessionid after integrating with hazelcast clustering.
