### ISSUE TITLE
configuration problem

### ISSUE THREAD

**Issue by bormarek** [hazelcast/hazelcast-tomcat-sessionmanager#32]
SEVERE: Error while connecting to cluster!
java.lang.IllegalStateException: Unable to connect to any address in the config!

i add 

        <cluster-members>
            <address>cacheserver-dev-3.atm:5701</address>
            <address>cacheserver-dev-3.atm:5702</address>
        </cluster-members>

into hazelcast.xml and put it in bin/

but nothing happen.

Any sugesstions?

**Comment by emre-aydin** [comment]
@bormarek can you please provide more information about your setup? Which version are you using? Can you share your Tomcat configuration?

**Comment by mesutcelik** [comment]
closing this one. please feel free to reopen if you have more questions.
