### ISSUE TITLE
Excessive logging on info level

### ISSUE THREAD

**Issue by bergander** [hazelcast/hazelcast-tomcat-sessionmanager#43]
Tomcat uses info as default logging level. And in `HazelcastSessionManager ` there are a couple of messages which should be on debug level, especially in the `findSession` method which is heavily used.

I propose to switch those log messages to debug level. Otherwise everyone needs to suppress them in the tomcat config. It's no good for performance to log messages on each request and several thousands of messages when doing a failover on a system with a lot of sessions, especially since the tomcat logging framework (juli) actually creates a stacktrace for each logged message (see log-method in `DirectJDKLog`).

**Comment by bergander** [comment]
@emre-aydin Thanks for the quick merge!

I missed one of the info-log messages so I created a new pull request for that one: #45

**Comment by emre-aydin** [comment]
Handled by https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/pull/44 and https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/pull/45
