### ISSUE TITLE
Tomcat 6 dependency in 8 module

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast-tomcat-sessionmanager#5]
It appears the core module depends on Tomcat 6, which has an `attributes` field in `org.apache.catalina.session.StandardSession`, but that field is gone in Tomcat 8, leading to this:
```
java.lang.NoSuchFieldError: attributes
       at com.hazelcast.session.HazelcastSession.writeData(HazelcastSession.java:85)
```

**Comment by emrahkocaman** [comment]
Closing this issue as `attributes` field still exists in Tomcat 8. 
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.tomcat/tomcat-catalina/8.0.24/org/apache/catalina/session/StandardSession.java#StandardSession.0attributes

**Comment by emrahkocaman** [comment]
Problem starts with Tomcat 8.0.35. Here is a similar problem.
https://github.com/magro/memcached-session-manager/commit/aa084dc1fe481101eac395654631abb1fd7e49d7
