### ISSUE TITLE
Why is Tomcat 7 no longer supported?

### ISSUE THREAD

**Issue by helge79** [hazelcast/hazelcast-tomcat-sessionmanager#70]
I wanted to download the latest release 1.1.4 for Tomcat 7 and found none. From the commit history I saw it was disabled by #64 because tests failed. Unfortunately I do not see any more details.

For me the current snapshot causes no issues - see [my changes](https://github.com/helge79/hazelcast-tomcat-sessionmanager/commit/c62347b219ce3d44c8ff29ad8fd0e3813367d8a4) for details. The same applies to the tagged version 1.1.4 (just needed to change the parent version in Tomcat 7's `pom.xml`).

What am I missing here? If Tomcat 7 is not going to be supported in the future it would also be good to change the `README.md`.

**Comment by alparslanavci** [comment]
@helge79, we were working on some tests on our side, because of that we haven't released  `hazelcast-tomcat7-sessionmanager-1.1.4` yet. After the tests are completed, we will release it. 

However, the support for Tomcat 6 will be dropped and we will update the readme accordingly.

**Comment by alparslanavci** [comment]
@helge79, `hazelcast-tomcat7-sessionmanager-1.1.4` is now released. The artifacts are available at the [release page](https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/releases/tag/v1.1.4).

**Comment by alparslanavci** [comment]
Fixed by #71
