### ISSUE TITLE
Simplify Tomcat Session Manager with Spring-Boot 

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-tomcat-sessionmanager#73]
Initial prototype is located [here](https://github.com/alparslanavci/hazelcast-tomcat-sessionmanager/commit/d7a1774b94969addec9b3ee3b39afb23c6614788). 

Tomcat Session Manager should be purely operational so adding it to the classpath should easily switch on/off session replication.

**Comment by vivekvara** [comment]
This is quite a useful feature to quickly configure tomcat session manager.
