### ISSUE TITLE
Cuncurrent calls lead to no session found

### ISSUE THREAD

**Issue by Spentas** [hazelcast/hazelcast-tomcat-sessionmanager#84]
I understand there is a fix for the concurrent calls but it still persists, however less frequent 

tomcat85-sessionmanager:1.1.5
tomcat:8.5
hazelcast:3.9

```
[http-nio-8080-exec-4] com.hazelcast.session.HazelcastSessionManager.findSession Attempting to find sessionId: 303B2C10337479C99450A40D2B5E3FB6
[http-nio-8080-exec-4] com.hazelcast.session.HazelcastSessionManager.findSession Session found for: 303B2C10337479C99450A40D2B5E3FB6
[http-nio-8080-exec-5] com.hazelcast.session.HazelcastSessionManager.findSession Attempting to find sessionId: 303B2C10337479C99450A40D2B5E3FB6
[http-nio-8080-exec-5] com.hazelcast.session.HazelcastSessionManager.findSession No Session found for: 303B2C10337479C99450A40D2B5E3FB6
```

**Comment by Spentas** [comment]
#42 related issue, 
https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/blob/master/tomcat8/src/main/java/com/hazelcast/session/HazelcastSessionManager.java#L206

`sessionMap.get` is not threadsafe, when  `remove` you still can read from the map despite `sessionMap.lock` leads to No Session Found

**Comment by ghkarmseveer** [comment]
as I mentioned in #42  I get sessions lost unless I also lock around the get

**Comment by Spentas** [comment]
@ghkarmseveer Yes I did the same, my problem was that I had multiple instances of my app in the cluster and each instance could potentially ask for the session from hazelcast-server, so if one instance removes the session and the other tries to retrieve it, then there is a problem.
