### ISSUE TITLE
sessionDestroyed is not called after a failover

### ISSUE THREAD

**Issue by bergander** [hazelcast/hazelcast-tomcat-sessionmanager#89]
Due to the recent removal of the implementation of findSessions() method in HazelcastSessionManager, Tomcat will only expire local sessions.

So whenever a node has been shutdown the sessions created on that node will never be expired by Tomcat, only removed from the global session map by Hazelcast. And that means that the application won't get notified through the HttpSessionListener.sessionDestroyed() for those sessions.

I've created a patch to fix this issue by introducing a EntryExpiredListener on the session map which calls session.expire() if it's still valid. I also extended the AbstractSessionExpireTest class with test cases for this issue.

Have I understood this correctly? Is there a better way of fixing the issue?

**Comment by alparslanavci** [comment]
Hi @bergander, when a node is shutdown Hazelcast promotes its sessions' backups to primary on the other nodes. Thus, the sessions are still available in the cluster. This means they are still valid and not expired. 

Additionally, starting with v2.1, Hazelcast and Tomcat session expiration are separated and work independently. Please see the details here: https://github.com/hazelcast/hazelcast-tomcat-sessionmanager#setting-session-expiration-checks

Please let us know if you still think that this is an issue.

**Comment by bergander** [comment]
Yes, the sessions are still valid and not expired at the time one node is shutdown. But if no further activity is done on one session, then it will be expired in the future. And when that happens sessionDestroyed won't be called.

**Comment by alparslanavci** [comment]
Do we need to call sessionDestroyed? If no further activity is done on one session, they will be also expired by Tomcat itself because of the session timeout.

**Comment by bergander** [comment]
Well, in my opinion it breaks the contract of a HttpSessionListener if some sessions are skipped calling sessionDestroyed. And on a more practical note, in our case we do some clean up and statistics handling in our implementation of sessionDestroyed.

And Tomcat will only call sessionDestroyed on the local sessions, but it can't do that if it's shutdown before the session expires.

I can work around this issue in case you don't agree though.

**Comment by alparslanavci** [comment]
We decided to close this issue after researching some other implementations. Also, sessionDestroyed is always called when a session expires on local.
