### ISSUE TITLE
Session manager in client only mode doesn't handle HZ client SHUTDOWN

### ISSUE THREAD

**Issue by ycordier-pro** [hazelcast/hazelcast-tomcat-sessionmanager#91]
This issue is submitted after investigating some reconnection issue on the Hazelcast client as described here :
https://github.com/hazelcast/hazelcast/issues/17062

Since HZ 3.12, it seems that the client will not handle automatic reconnection whenever the cluster members are restarted with different IP addresses (always the case in the docker world).
In such a scenario, whenever a cluster member is restarted, the client is not capable of reconnecting to its new IP address, and if at some point all the members have been restarted, the client will completely be unable to connect to any member and will SHUTDOWN.
As proposed in the linked issue and in the google group here : https://groups.google.com/forum/#!msg/hazelcast/6OM_msgJvzg/kDi06y29CQAJ
The solution is to register a LifecycleListener on the client to be notified whenever such a SHUTDOWN condition is encountered, and then fully re-instanciate/restart the HZ client from scratch so that it resolves again the member names provided in the configuration.
In the tomcat replication manager, this can be implemented in the session manager.

As stated in the linked issue, I am finishing a patch that I will propose for such automatic reconnection whenever a client SHUTDOWN is encountered.

**Comment by alparslanavci** [comment]
Hi @ycordier-pro, thanks for the contribution. We would like to see your patch. It will be also good to keep an eye on https://github.com/hazelcast/hazelcast/issues/17062, we won't need to add anything on Tomcat Session Manager side if they fix it.

**Comment by ycordier-pro** [comment]
I finished the patch but I have troubles with unit tests :( 
They always fail with errors like "

**Comment by ycordier-pro** [comment]
Thanks for your reply, I've finished the patch but I have troubles with the unit tests.
They are always failing with errors like:
```
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 19.964 sec <<< FAILURE! - in com.hazelcast.session.nonsticky.Tomcat7P2PNonStickySessionsTest
com.hazelcast.session.nonsticky.Tomcat7P2PNonStickySessionsTest  Time elapsed: 2.615 sec  <<< ERROR!
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='SESSION-REPLICATION-INSTANCE', node=[127.0.0.1]:5701}]
```
So it's not a real unit test failure per say, it looks like some threads were still up at the end of the test, which causes some exception. Do you know if it's "normal" ?

As for the linked bug, I think that even if they fix the IP change issue, we can still always have a case where all the cluster members could be down for some (bad) reason. In this case the HZ client will go in SHUTDOWN and the current tomcat session manager will never be able to reconnect (the client instance is "dead") so my patch would still be valuable anyways I think, for automatic reconnection of the client in any case it would go to SHUTDOWN.

**Comment by alparslanavci** [comment]
Could you please share your patch as a `DRAFT` pull request? It'll make easier to check the error.

> As for the linked bug, I think that even if they fix the IP change issue, we can still always have a case where all the cluster members could be down for some (bad) reason. In this case the HZ client will go in SHUTDOWN and the current tomcat session manager will never be able to reconnect (the client instance is "dead") so my patch would still be valuable anyways I think, for automatic reconnection of the client in any case it would go to SHUTDOWN.

Hazelcast client has its own [reconnection mechanism](https://docs.hazelcast.org/docs/latest/manual/html-single/#java-client-connection-strategy) which can be used in these kind of regular shutdown scenarios. I believe it'll be much simpler to leave this to Hazelcast client. But if it doesn't support a feature that we need, that we can go ahead and implement a solution on Tomcat Session Manager.

**Comment by ycordier-pro** [comment]
You can check my proposed patch/fix in the following repo: 
https://github.com/ycordier-pro/hazelcast-tomcat-sessionmanager
(I created a new one since I was not authorized to create a branch on this one)

**Comment by ycordier-pro** [comment]
As discussed I created a draft pull request here:
https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/pull/92

**Comment by alparslanavci** [comment]
Fixed accordingly with https://github.com/hazelcast/hazelcast/pull/17239
