### ISSUE TITLE
Question about sessions sharing in K8s

### ISSUE THREAD

**Issue by bianchi2** [hazelcast/hazelcast-tomcat-sessionmanager#95]
I am using K8s hazelcast config, and my multiple instances of tomcat servers find each other, a cluster is created. I can also see that session are shared ok. However, there's one use case that fails for me. A new member does not seem to get sessions from existing members. So, for instance, when there are 2 replicas running, I log into my webapp, and then hit F5 to see that I am landing on different containers - everything works as expected, and I logged it and both Tomcats have my session. However, when I add a new Tomcat instance, this one does not seem to have those sessions, though I clearly see in log that I have 3 members now:

```
Members {size:3, ver:5} [
	Member [10.244.4.121]:5701 - 4e9c2665-670c-4422-b5fd-86499d7bc68d
	Member [10.244.8.22]:5701 - f65a86f6-a49f-4f94-8705-6220d8ca7bce this
	Member [10.244.7.117]:5701 - 07a34f13-676d-4f46-b416-b696e006a441
]
```
Is this expected or there's some configuration that I am missing?

Thanks!

**Comment by alparslanavci** [comment]
Hi @bianchi2, are you using non-sticky sessions?

**Comment by bianchi2** [comment]
Yes, default configs as per https://github.com/hazelcast/hazelcast-tomcat-sessionmanager#deploying-p2p-for-tomcat

**Comment by alparslanavci** [comment]
Hi @bianchi2, I created a simple unit test and it looks it is working as expected. Please see it below:

```
    @Test(timeout = 60000)
    public void testNewInstance() throws Exception {
        CookieStore cookieStore = new BasicCookieStore();
        executeRequest("write", SERVER_PORT_1, cookieStore);

        String value = executeRequest("read", SERVER_PORT_1, cookieStore);
        assertEquals("value", value);

        value = executeRequest("read", SERVER_PORT_2, cookieStore);
        assertEquals("value", value);

        WebContainerConfigurator<?> instance3 = getWebContainerConfigurator();
        int serverPort3 = findFreeTCPPort();
        instance3.port(serverPort3).sticky(false).clientOnly(false).sessionTimeout(10).start();

        value = executeRequest("read", serverPort3, cookieStore);
        assertEquals("value", value);
    }
```

Do you have any reproducer that you can share with us? Maybe I am missing a point.

**Comment by alparslanavci** [comment]
@bianchi2, do you have any updates? Are you still facing this issue?

**Comment by bianchi2** [comment]
@alparslanavci it was smth in the app itself. Thanks for your support.
