### ISSUE TITLE
Inconsistent sessionId in the first request after a failover

### ISSUE THREAD

**Issue by jorditpuig** [hazelcast/hazelcast-tomcat-sessionmanager#96]
I am not confident that this is really an issue so this is more of a question. When a failover happens with stickiness enabled, the first request of a session assigned to the server that failed (let `.host1`) is expected to have a suffix (i.e. _jvmRoute_) that will not match the _jvmRoute_ of the healthy host (let `.host2`). After digging a bit I have noticed that the _HazelcastSessionChangeValve_ will call an internal Tomcat API `request.changeSessionId()` to change the sessionId so that it matches the new _jvmRoute_. This means that after passing from the valve the value returned from the servlet API call `request.getRequestedSessionId()` will have the suffix of the healthy host `.host2`. In addition, examining the headers of the response one can see that this call also adds a new `Set-Cookie` header with the updated sessionId. `getSession().getId()` however still returns the id ending in `.host1`! 

I believe that this is confusing given that the Servlet spec states about `HttpServletRequest.getRequestedSessionId()`: 

> Returns the session ID specified by the client. This may not be the same as the ID of the current valid session for this request. If the client did not specify a session ID, this method returns null.

I understand that maybe this is the best way that Tomcat provides to change the sessionId using its internal API but shouldn't it at least be consistent with the id stored in the session returned by `getSession()`. This might be important for any servlet filters that need the sessionId of the validated session and not the information passed by the client (i.e., returned by `getRequestedSessionId`).

**Comment by alparslanavci** [comment]
Hi @jorditpuig, thanks for the detailed question. However, the jvmRoute is also updated on server side since `SessionManager#updateJvmRouteForSession` API is called in the `HazelcastSessionChangeValve`. 

Did I miss anything on your question?

**Comment by jorditpuig** [comment]
First of all, thanks a lot for your quick answer @alparslanavci! I was not able to dig in this issue till now.

The visible issue is that `HttpServletRequest#getSession` returns the old id. I believe that this indicates that somehow the "first after failover" request keeps in `Request#session` a reference to a stale session object that in fact has a session Id with the jvmRoute of the server that is failing.

I have investigated a bit more the issue and it really seems that the Request has a reference to the stale session. I think this is because `SessionManager#updateJvmRouteForSession` updates the session found in the `sessionMap` of the session manager but not the one in the field `Request.session`. If I am not mistaken these two objects are not the same since `sessionMap#get` seems to be returning a new object each time it is called. In fact the reference to the session found in the Request is established by a call to `SessionManager#findSession` but the one used in `SessionManager#updateJvmRouteForSession` is by calling `sessionMap#get` again.

I have also tried the following scenario. Let the first request after a failover to be a POST request that modifies the Session. I have verified that any attributes added to the Session are lost since they are applied to a Session that is no longer in the distributed Map of the sessionManager.

Reviewing the code of `org.apache.catalina.connector.HttpServletRequest` it seems that a way to fix this inconsistency is to "invalidate" the Session stored in the request calling  something like `request.getSession().invalidate()` in `HazelcastSessionChangeValve#handleTomcatSessionChange()`. Marking the session as invalid results to any call to `Request#getSession` (delegating to `Request#doGetSession`) fetching the one with the new session id (i.e., `Request#requestedSessionId`) since it finally calls `SessionManager#findSession`. I have quickly tested this solution and it seems to be solving the issue with the missed modifications during failover that I mentioned above.

Another way to fix this would be having `SessionManager#updateJvmRouteForSession` calling `SessionManager#findSession` so that it updates the `jvmRoute` suffix using a reference to the object stored in `SessionManager#sessions` and not getting a new one from `SessionManager#sessionMap`.

**Comment by alparslanavci** [comment]
Thanks for the detailed reply @jorditpuig! It looks we can add an invalidation call at the end of the valve. I will check it and send a PR.
