### ISSUE TITLE
HttpSessionListener.sessionCreated calls twice

### ISSUE THREAD

**Issue by chynten** [hazelcast/hazelcast-tomcat-sessionmanager#98]
`com.hazelcast.session.HazelcastSessionManager.createSession` has a call of `session.setId(newSessionId)` from class `org.apache.catalina.session.StandardSession`

`org.apache.catalina.session.StandardSession` internally calls `setId(id, true);` where true is notify. If notify is true then it `calls tellNew();` methodd.

`Now back to com.hazelcast.session.HazelcastSessionManager.createSession` after calling `session.setId(newSessionId)` it calls  `session.tellNew();`

This creates `tellNew()` call twice which eventually results in calling `sessionCreated` call twice.

**Comment by alparslanavci** [comment]
Thanks for reporting this, it looks like a bug.
